---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - pwd
      - ls -al
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
