version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - |
        if [ "$CODEBUILD_SOURCE_REPO_URL" == "https://github.com/vikaskumarp1061/angular-app.git" ]; then
          pwd
          ls -al
        fi
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
